# Generated by Django 6.0 on 2025-12-09 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapp", "0003_priority_task_completed_date_task_end_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="task",
            name="date",
        ),
    ]
